#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: kube-jenkins-deployment
#  namespace: jenkins-namespace
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/enable-cors: "true"

#spec:
#  tls:
#    - hosts:
#        - jenkins-ingress
#      secretName: internal-tls
#  rules:
#    - host: jenkins-ingress
#      http:
#        paths:
#          - path: /authen-api/(.*)
#            backend:
#              serviceName: jenkins-service
#              servicePort: jenkins-port
